apiVersion: polocloud.de/v1
kind: Group
metadata: # ATTENTION: This metadata cannot be changed after creation!
  name: lobby
  namespace: polocloud
spec:
  base:
    image: 10.99.214.62:5000/lobby:latest
    environment:
      - PLATFORM=PAPER
    ports:
      - port: 25565
        protocol: TCP
  maintenance: false
  minOnline: 1
  maxOnline: 5
  maxMemory: 1028
  fallback: true