apiVersion: v1
kind: Namespace
metadata:
  name: polocloud
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: polocloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
  namespace: agent
rules:
  - apiGroups: [ "", "apps", "apiextensions.k8s.io" ]
    resources: [ "pods", "services", "configmaps", "secrets", "customresourcedefinitions" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-rolebinding
  namespace: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: nextcluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: polocloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      serviceAccountName: agent
      containers:
        - name: agent
          image: polocloud-agent:latest
          imagePullPolicy: Never
          env:
            - name: KUBERNETES_AUTH_TRYKUBECONFIG
              value: "false"
