version: "3.9"

services:
  agent:
    image: polocloud:development
    volumes:
      - C:\Users\mirco\Desktop\te\:/cloud/local
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
