name: Deploy Docs

on:
  push:
    branches:
      - development  # oder main, je nach deinem Default-Branch

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Mintlify CLI
        run: npm install -g mint

      - name: Install project dependencies
        working-directory: ./docs
        run: npm install

      - name: Build docs
        working-directory: ./docs
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/out
